-- ============================================
-- PERFORMANCE REPORTS TABLE
-- Stores computed performance summaries per student per class per period.
-- Generated by teachers/system; viewed by students and teachers.
-- ============================================

CREATE TABLE IF NOT EXISTS public.performance_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  class_id UUID NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
  period TEXT NOT NULL, -- e.g. "2024-Q1", "Feb 2024"
  avg_marks NUMERIC(5, 2) DEFAULT 0,
  attendance_pct NUMERIC(5, 2) DEFAULT 0,
  total_exams INT DEFAULT 0,
  total_present INT DEFAULT 0,
  total_absent INT DEFAULT 0,
  remarks TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE(student_id, class_id, period) -- one report per student per class per period
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_perf_student_id ON public.performance_reports(student_id);
CREATE INDEX IF NOT EXISTS idx_perf_class_id ON public.performance_reports(class_id);
CREATE INDEX IF NOT EXISTS idx_perf_period ON public.performance_reports(period);

-- Enable RLS
ALTER TABLE public.performance_reports ENABLE ROW LEVEL SECURITY;

-- Policy: Authenticated users can view (backend enforces student-only-own-data)
CREATE POLICY "Authenticated users can view performance reports"
  ON public.performance_reports FOR SELECT
  USING (auth.role() = 'authenticated');

-- Policy: Authenticated users can insert (teacher role enforced at backend)
CREATE POLICY "Authenticated users can insert performance reports"
  ON public.performance_reports FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- Policy: Creator can update
CREATE POLICY "Creators can update performance reports"
  ON public.performance_reports FOR UPDATE
  USING (auth.uid() = created_by);

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_performance_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_performance_updated_at
  BEFORE UPDATE ON public.performance_reports
  FOR EACH ROW
  EXECUTE FUNCTION public.update_performance_updated_at();

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.performance_reports;
